services:
  mongoo:
    image: mongo
    container_name: mongocontainer
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - appnet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpass
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpass@mongoo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false
    networks:
      - appnet
    depends_on:
      - mongoo

  estudiantes:
    image: andres496/estudiantes:latest
    networks:
      - appnet
    ports:
      - "3001:3001"
    environment:
      MONGO_URL: mongodb://admin:adminpass@mongoo:27017/?authSource=admin
    depends_on:
      - mongoo

  salas:
    image: andres496/salas:latest
    networks:
      - appnet
    ports:
      - "3002:3002"
    environment:
      MONGO_URL: mongodb://admin:adminpass@mongoo:27017/?authSource=admin
    depends_on:
      - mongoo

  prestamos:
    image: andres496/prestamos:latest
    networks:
      - appnet
    ports:
      - "3003:3003"
    environment:
      MONGO_URL: mongodb://admin:adminpass@mongoo:27017/?authSource=admin
    depends_on:
      - mongoo
  
  frontend:
    image: andres496/frontend:latest
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      - estudiantes
      - salas
      - prestamos

networks:
  appnet:
    driver: bridge

volumes:
  mongo-data:
